import type { RegistryEntry } from "../../shared.ts";

export const windsurfProvider: RegistryEntry = {
  id: "windsurf",
  alias: "ws",
  format: "windsurf",
  executor: "windsurf",
  // Devin direct Connect endpoint — authenticated by Windsurf session token.
  // The executor exchanges it for a JWT and may use the account-specific host
  // returned by GetUserJwt for the chat request.
  baseUrl: "https://server.codeium.com",
  authType: "oauth",
  authHeader: "Authorization",
  authPrefix: "Bearer ",
  defaultContextLength: 200000,
  // Model IDs verified against model_configs_v2.bin from Devin CLI binary (2026.5.x).
  // dot-notation = OmniRoute ID; executor MODEL_ALIAS_MAP maps it to Windsurf modelUid.
  // Catalog synced from Devin's live ApiServerService/GetCascadeModelConfigs
  // (185 configs -> 147 callable model UIDs) on 2026-07-26. Regenerate with the
  // same RPC rather than hand-editing: display name = field 1, wire UID = field 22
  // (older models carry it in field 23 behind a MODEL_* enum), context = field 18.
  // dot-notation = OmniRoute ID; executor MODEL_ALIAS_MAP maps it to the wire UID.
  models: [
    // ── Cognition / SWE ─────────────────────────────────────────────────────
    { id: "swe-1.6", name: "SWE-1.6", contextLength: 200000, toolCalling: true },
    { id: "swe-1.6-fast", name: "SWE-1.6 Fast", contextLength: 200000, toolCalling: true },
    { id: "swe-1.7", name: "SWE-1.7 Max", contextLength: 262000, toolCalling: true },
    {
      id: "swe-1.7-lightning",
      name: "SWE-1.7 Lightning",
      contextLength: 202752,
      toolCalling: true,
    },
    { id: "swe-1.7-medium", name: "SWE-1.7 Medium", contextLength: 262000, toolCalling: true },
    // ── Anthropic Claude ────────────────────────────────────────────────────
    {
      id: "claude-5-fable-high",
      name: "Claude Fable 5 High",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-5-fable-low",
      name: "Claude Fable 5 Low",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-5-fable-max",
      name: "Claude Fable 5 Max",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-5-fable-medium",
      name: "Claude Fable 5 Medium",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-5-fable-xhigh",
      name: "Claude Fable 5 XHigh",
      contextLength: 1000000,
      toolCalling: true,
    },
    { id: "claude-opus-4.5", name: "Claude Opus 4.5", contextLength: 200000, toolCalling: true },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6", contextLength: 200000, toolCalling: true },
    {
      id: "claude-opus-4.6-1m",
      name: "Claude Opus 4.6 1M",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.6-thinking",
      name: "Claude Opus 4.6 Thinking",
      contextLength: 200000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.6-thinking-1m",
      name: "Claude Opus 4.6 Thinking 1M",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.7-high",
      name: "Claude Opus 4.7 High",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.7-low",
      name: "Claude Opus 4.7 Low",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.7-max",
      name: "Claude Opus 4.7 Max",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.7-medium",
      name: "Claude Opus 4.7 Medium",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.7-xhigh",
      name: "Claude Opus 4.7 XHigh",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.8-high",
      name: "Claude Opus 4.8 High",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.8-high-fast",
      name: "Claude Opus 4.8 High Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.8-low",
      name: "Claude Opus 4.8 Low",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.8-low-fast",
      name: "Claude Opus 4.8 Low Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.8-max",
      name: "Claude Opus 4.8 Max",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.8-max-fast",
      name: "Claude Opus 4.8 Max Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.8-medium",
      name: "Claude Opus 4.8 Medium",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.8-medium-fast",
      name: "Claude Opus 4.8 Medium Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.8-xhigh",
      name: "Claude Opus 4.8 XHigh",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.8-xhigh-fast",
      name: "Claude Opus 4.8 XHigh Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-5-high",
      name: "Claude Opus 5 High",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-5-high-fast",
      name: "Claude Opus 5 High Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-5-low",
      name: "Claude Opus 5 Low",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-5-low-fast",
      name: "Claude Opus 5 Low Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-5-max",
      name: "Claude Opus 5 Max",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-5-max-fast",
      name: "Claude Opus 5 Max Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-5-medium",
      name: "Claude Opus 5 Medium",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-5-medium-fast",
      name: "Claude Opus 5 Medium Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-5-xhigh",
      name: "Claude Opus 5 XHigh",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-opus-5-xhigh-fast",
      name: "Claude Opus 5 XHigh Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-4.5",
      name: "Claude Sonnet 4.5",
      contextLength: 200000,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-4.6",
      name: "Claude Sonnet 4.6",
      contextLength: 200000,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-4.6-1m",
      name: "Claude Sonnet 4.6 1M",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-4.6-thinking",
      name: "Claude Sonnet 4.6 Thinking",
      contextLength: 200000,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-4.6-thinking-1m",
      name: "Claude Sonnet 4.6 Thinking 1M",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-5-high",
      name: "Claude Sonnet 5 High",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-5-low",
      name: "Claude Sonnet 5 Low",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-5-max",
      name: "Claude Sonnet 5 Max",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-5-medium",
      name: "Claude Sonnet 5 Medium",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-5-xhigh",
      name: "Claude Sonnet 5 XHigh",
      contextLength: 1000000,
      toolCalling: true,
    },
    // ── OpenAI ──────────────────────────────────────────────────────────────
    { id: "gpt-5.1", name: "GPT-5.1 No Thinking", contextLength: 384000, toolCalling: true },
    { id: "gpt-5.2", name: "GPT-5.2 Low Thinking", contextLength: 384000, toolCalling: true },
    {
      id: "gpt-5.3-codex-high",
      name: "GPT-5.3-Codex High",
      contextLength: 400000,
      toolCalling: true,
    },
    {
      id: "gpt-5.3-codex-high-priority",
      name: "GPT-5.3-Codex High Fast",
      contextLength: 400000,
      toolCalling: true,
    },
    {
      id: "gpt-5.3-codex-low",
      name: "GPT-5.3-Codex Low",
      contextLength: 400000,
      toolCalling: true,
    },
    {
      id: "gpt-5.3-codex-low-priority",
      name: "GPT-5.3-Codex Low Fast",
      contextLength: 400000,
      toolCalling: true,
    },
    {
      id: "gpt-5.3-codex-medium",
      name: "GPT-5.3-Codex Medium",
      contextLength: 400000,
      toolCalling: true,
    },
    {
      id: "gpt-5.3-codex-medium-priority",
      name: "GPT-5.3-Codex Medium Fast",
      contextLength: 400000,
      toolCalling: true,
    },
    {
      id: "gpt-5.3-codex-xhigh",
      name: "GPT-5.3-Codex X-High",
      contextLength: 400000,
      toolCalling: true,
    },
    {
      id: "gpt-5.3-codex-xhigh-priority",
      name: "GPT-5.3-Codex XHigh Fast",
      contextLength: 400000,
      toolCalling: true,
    },
    { id: "gpt-5.4-high", name: "GPT-5.4 High Thinking", contextLength: 272000, toolCalling: true },
    {
      id: "gpt-5.4-high-priority",
      name: "GPT-5.4 High Thinking Fast",
      contextLength: 272000,
      toolCalling: true,
    },
    { id: "gpt-5.4-low", name: "GPT-5.4 Low Thinking", contextLength: 272000, toolCalling: true },
    {
      id: "gpt-5.4-low-priority",
      name: "GPT-5.4 Low Thinking Fast",
      contextLength: 272000,
      toolCalling: true,
    },
    {
      id: "gpt-5.4-medium",
      name: "GPT-5.4 Medium Thinking",
      contextLength: 272000,
      toolCalling: true,
    },
    {
      id: "gpt-5.4-medium-priority",
      name: "GPT-5.4 Medium Thinking Fast",
      contextLength: 272000,
      toolCalling: true,
    },
    {
      id: "gpt-5.4-mini-high",
      name: "GPT-5.4 Mini High Thinking",
      contextLength: 400000,
      toolCalling: true,
    },
    {
      id: "gpt-5.4-mini-low",
      name: "GPT-5.4 Mini Low Thinking",
      contextLength: 400000,
      toolCalling: true,
    },
    {
      id: "gpt-5.4-mini-medium",
      name: "GPT-5.4 Mini Medium Thinking",
      contextLength: 400000,
      toolCalling: true,
    },
    {
      id: "gpt-5.4-mini-xhigh",
      name: "GPT-5.4 Mini XHigh Thinking",
      contextLength: 400000,
      toolCalling: true,
    },
    { id: "gpt-5.4-none", name: "GPT-5.4 No Thinking", contextLength: 272000, toolCalling: true },
    {
      id: "gpt-5.4-none-priority",
      name: "GPT-5.4 No Thinking Fast",
      contextLength: 272000,
      toolCalling: true,
    },
    {
      id: "gpt-5.4-xhigh",
      name: "GPT-5.4 XHigh Thinking",
      contextLength: 272000,
      toolCalling: true,
    },
    {
      id: "gpt-5.4-xhigh-priority",
      name: "GPT-5.4 XHigh Thinking Fast",
      contextLength: 272000,
      toolCalling: true,
    },
    { id: "gpt-5.5-high", name: "GPT-5.5 High Thinking", contextLength: 272000, toolCalling: true },
    {
      id: "gpt-5.5-high-priority",
      name: "GPT-5.5 High Thinking Fast",
      contextLength: 272000,
      toolCalling: true,
    },
    { id: "gpt-5.5-low", name: "GPT-5.5 Low Thinking", contextLength: 272000, toolCalling: true },
    {
      id: "gpt-5.5-low-priority",
      name: "GPT-5.5 Low Thinking Fast",
      contextLength: 272000,
      toolCalling: true,
    },
    {
      id: "gpt-5.5-medium",
      name: "GPT-5.5 Medium Thinking",
      contextLength: 272000,
      toolCalling: true,
    },
    {
      id: "gpt-5.5-medium-priority",
      name: "GPT-5.5 Medium Thinking Fast",
      contextLength: 272000,
      toolCalling: true,
    },
    { id: "gpt-5.5-none", name: "GPT-5.5 No Thinking", contextLength: 272000, toolCalling: true },
    {
      id: "gpt-5.5-none-priority",
      name: "GPT-5.5 No Thinking Fast",
      contextLength: 272000,
      toolCalling: true,
    },
    {
      id: "gpt-5.5-xhigh",
      name: "GPT-5.5 XHigh Thinking",
      contextLength: 272000,
      toolCalling: true,
    },
    {
      id: "gpt-5.5-xhigh-priority",
      name: "GPT-5.5 XHigh Thinking Fast",
      contextLength: 272000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-luna-high",
      name: "GPT-5.6 Luna High Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-luna-high-priority",
      name: "GPT-5.6 Luna High Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-luna-low",
      name: "GPT-5.6 Luna Low Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-luna-low-priority",
      name: "GPT-5.6 Luna Low Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-luna-max",
      name: "GPT-5.6 Luna Max Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-luna-medium",
      name: "GPT-5.6 Luna Medium Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-luna-medium-priority",
      name: "GPT-5.6 Luna Medium Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-luna-none",
      name: "GPT-5.6 Luna No Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-luna-none-priority",
      name: "GPT-5.6 Luna No Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-luna-xhigh",
      name: "GPT-5.6 Luna XHigh Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-luna-xhigh-priority",
      name: "GPT-5.6 Luna XHigh Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-sol-high",
      name: "GPT-5.6 Sol High Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-sol-high-priority",
      name: "GPT-5.6 Sol High Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-sol-low",
      name: "GPT-5.6 Sol Low Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-sol-low-priority",
      name: "GPT-5.6 Sol Low Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-sol-max",
      name: "GPT-5.6 Sol Max Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-sol-medium",
      name: "GPT-5.6 Sol Medium Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-sol-medium-priority",
      name: "GPT-5.6 Sol Medium Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-sol-none",
      name: "GPT-5.6 Sol No Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-sol-none-priority",
      name: "GPT-5.6 Sol No Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-sol-xhigh",
      name: "GPT-5.6 Sol XHigh Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-sol-xhigh-priority",
      name: "GPT-5.6 Sol XHigh Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-terra-high",
      name: "GPT-5.6 Terra High Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-terra-high-priority",
      name: "GPT-5.6 Terra High Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-terra-low",
      name: "GPT-5.6 Terra Low Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-terra-low-priority",
      name: "GPT-5.6 Terra Low Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-terra-max",
      name: "GPT-5.6 Terra Max Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-terra-medium",
      name: "GPT-5.6 Terra Medium Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-terra-medium-priority",
      name: "GPT-5.6 Terra Medium Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-terra-none",
      name: "GPT-5.6 Terra No Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-terra-none-priority",
      name: "GPT-5.6 Terra No Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-terra-xhigh",
      name: "GPT-5.6 Terra XHigh Thinking",
      contextLength: 1000000,
      toolCalling: true,
    },
    {
      id: "gpt-5.6-terra-xhigh-priority",
      name: "GPT-5.6 Terra XHigh Thinking Fast",
      contextLength: 1000000,
      toolCalling: true,
    },
    // ── Google Gemini ───────────────────────────────────────────────────────
    {
      id: "gemini-3.0-flash",
      name: "Gemini 3 Flash Minimal",
      contextLength: 1048576,
      toolCalling: true,
    },
    {
      id: "gemini-3.1-pro-high",
      name: "Gemini 3.1 Pro High Thinking",
      contextLength: 1048576,
      toolCalling: true,
    },
    {
      id: "gemini-3.1-pro-low",
      name: "Gemini 3.1 Pro Low Thinking",
      contextLength: 1048576,
      toolCalling: true,
    },
    {
      id: "gemini-3.5-flash-high",
      name: "Gemini 3.5 Flash High",
      contextLength: 1048576,
      toolCalling: true,
    },
    {
      id: "gemini-3.5-flash-low",
      name: "Gemini 3.5 Flash Low",
      contextLength: 1048576,
      toolCalling: true,
    },
    {
      id: "gemini-3.5-flash-medium",
      name: "Gemini 3.5 Flash Medium",
      contextLength: 1048576,
      toolCalling: true,
    },
    {
      id: "gemini-3.5-flash-minimal",
      name: "Gemini 3.5 Flash Minimal",
      contextLength: 1048576,
      toolCalling: true,
    },
    {
      id: "gemini-3.6-flash-high",
      name: "Gemini 3.6 Flash High",
      contextLength: 1048576,
      toolCalling: true,
    },
    {
      id: "gemini-3.6-flash-low",
      name: "Gemini 3.6 Flash Low",
      contextLength: 1048576,
      toolCalling: true,
    },
    {
      id: "gemini-3.6-flash-medium",
      name: "Gemini 3.6 Flash Medium",
      contextLength: 1048576,
      toolCalling: true,
    },
    {
      id: "gemini-3.6-flash-minimal",
      name: "Gemini 3.6 Flash Minimal",
      contextLength: 1048576,
      toolCalling: true,
    },
    // ── DeepSeek ────────────────────────────────────────────────────────────
    { id: "deepseek-v4", name: "DeepSeek V4 Pro", contextLength: 1048576 },
    // ── Moonshot Kimi ───────────────────────────────────────────────────────
    { id: "kimi-k2-6", name: "Kimi K2.6", contextLength: 262144 },
    { id: "kimi-k2-7", name: "Kimi K2.7", contextLength: 262144 },
    // ── Zhipu GLM ───────────────────────────────────────────────────────────
    { id: "glm-5.2", name: "GLM-5.2 High", contextLength: 200000 },
    { id: "glm-5.2-1m", name: "GLM-5.2 High 1M", contextLength: 1000000 },
    { id: "glm-5.2-max", name: "GLM-5.2 Max", contextLength: 200000 },
    { id: "glm-5.2-max-1m", name: "GLM-5.2 Max 1M", contextLength: 1000000 },
    { id: "glm-5.2-none", name: "GLM-5.2 No Thinking", contextLength: 200000 },
    {
      id: "glm-5.2-none-1m",
      name: "GLM-5.2 No Thinking 1M",
      contextLength: 1000000,
    },
    // ── xAI Grok ────────────────────────────────────────────────────────────
    { id: "grok-4.5-high", name: "Grok 4.5 High", contextLength: 500000 },
    { id: "grok-4.5-low", name: "Grok 4.5 Low", contextLength: 500000 },
    { id: "grok-4.5-medium", name: "Grok 4.5 Medium", contextLength: 500000 },
    // ── Other ───────────────────────────────────────────────────────────────
    { id: "inkling-high", name: "Inkling High", contextLength: 1048576 },
    { id: "inkling-low", name: "Inkling Low", contextLength: 1048576 },
    { id: "inkling-max", name: "Inkling Max", contextLength: 1048576 },
    { id: "inkling-medium", name: "Inkling Medium", contextLength: 1048576 },
    { id: "inkling-none", name: "Inkling None", contextLength: 1048576 },
    { id: "inkling-xhigh", name: "Inkling X-High", contextLength: 1048576 },
    {
      id: "nemotron-3-ultra-nvfp4",
      name: "Nemotron 3 Ultra",
      contextLength: 262144,
    },
  ],
};
